# Generated by Django 5.2 on 2025-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_notes_file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='destination_country',
            field=models.CharField(default='canada', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='duration_of_stay',
            field=models.CharField(default='1 month', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='education_level',
            field=models.CharField(default='masters', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='a1@a1.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='fullname', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(default='single', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(default='tunisian', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='occupation',
            field=models.CharField(default='qa tester', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='passport_number',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default=11111111, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='purpose_of_travel',
            field=models.CharField(default='tourism', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='supporting_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_type',
            field=models.CharField(default='pro', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
